spring.application.name=catalogy
spring.datasource.url=jdbc:postgresql://localhost:5432/catalogly
spring.datasource.username=postgres
spring.datasource.password=1131
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false
